export const ActionTypes = Object.freeze({
  ADD_COMPONENT: 'ADD_COMPONENT',
  UPDATE_COMPONENT: 'UPDATE_COMPONENT',
  DELETE_COMPONENT: 'DELETE_COMPONENT',
  MOVE_COMPONENT: 'MOVE_COMPONENT',
  RESIZE_COMPONENT: 'RESIZE_COMPONENT',
  ADD_CONNECTOR: 'ADD_CONNECTOR',
  UPDATE_CONNECTOR: 'UPDATE_CONNECTOR',
  DELETE_CONNECTOR: 'DELETE_CONNECTOR',
  ADD_FLOW_STEP: 'ADD_FLOW_STEP',
  UPDATE_FLOW_STEP: 'UPDATE_FLOW_STEP',
  REORDER_FLOW_STEPS: 'REORDER_FLOW_STEPS',
  SET_SELECTION: 'SET_SELECTION',
  SET_VIEWPORT: 'SET_VIEWPORT',
  SET_EDITOR_MODE: 'SET_EDITOR_MODE',
  ENTER_PRESENTATION_MODE: 'ENTER_PRESENTATION_MODE',
  EXIT_PRESENTATION_MODE: 'EXIT_PRESENTATION_MODE',
  START_ANIMATION: 'START_ANIMATION',
  ADVANCE_ANIMATION: 'ADVANCE_ANIMATION',
  STOP_ANIMATION: 'STOP_ANIMATION',
  REPLACE_STATE: 'REPLACE_STATE',
});

export const actions = {
  addComponent: component => ({ type: ActionTypes.ADD_COMPONENT, payload: { component } }),
  updateComponent: (id, changes) => ({ type: ActionTypes.UPDATE_COMPONENT, payload: { id, changes } }),
  deleteComponent: id => ({ type: ActionTypes.DELETE_COMPONENT, payload: { id } }),
  addConnector: connector => ({ type: ActionTypes.ADD_CONNECTOR, payload: { connector } }),
  updateConnector: (id, changes) => ({ type: ActionTypes.UPDATE_CONNECTOR, payload: { id, changes } }),
  deleteConnector: id => ({ type: ActionTypes.DELETE_CONNECTOR, payload: { id } }),
  addFlowStep: flowStep => ({ type: ActionTypes.ADD_FLOW_STEP, payload: { flowStep } }),
  updateFlowStep: (id, changes) => ({ type: ActionTypes.UPDATE_FLOW_STEP, payload: { id, changes } }),
  setSelection: selection => ({ type: ActionTypes.SET_SELECTION, payload: { selection } }),
  setViewport: viewport => ({ type: ActionTypes.SET_VIEWPORT, payload: { viewport } }),
};
